// src/models/board-state.js
// Creates, validates, and updates the serializable board state.
// Connects to: config/board-config.js and services/board-controller.js.
// Created: 2026-06-18

import {
  CARD_DESCRIPTION_MAX_LENGTH,
  CARD_TITLE_MAX_LENGTH,
  COLUMNS,
  INITIAL_CARDS,
} from "../config/board-config.js";

/**
 * Creates a fresh board state from the configured sample cards.
 * @returns {{cards: Array<object>}} A mutable board state copy.
 */
export function createInitialState() {
  return { cards: INITIAL_CARDS.map((card) => ({ ...card })) };
}

/**
 * Checks whether unknown data has the expected board-state shape.
 * @param {unknown} state Candidate state loaded from persistence.
 * @returns {boolean} Whether the candidate is safe to render.
 */
export function isValidState(state) {
  if (!state || typeof state !== "object" || !Array.isArray(state.cards)) {
    return false;
  }

  const columnIds = new Set(COLUMNS.map((column) => column.id));
  const cardIds = new Set();

  return state.cards.every((card) => {
    const isValidCard =
      card &&
      typeof card === "object" &&
      typeof card.id === "string" &&
      card.id.length > 0 &&
      typeof card.title === "string" &&
      card.title.length > 0 &&
      card.title.length <= CARD_TITLE_MAX_LENGTH &&
      typeof card.description === "string" &&
      card.description.length <= CARD_DESCRIPTION_MAX_LENGTH &&
      columnIds.has(card.columnId) &&
      !cardIds.has(card.id);

    cardIds.add(card?.id);
    return isValidCard;
  });
}

/**
 * Returns a new state with one card moved to a valid destination column.
 * @param {{cards: Array<object>}} state Current board state.
 * @param {string} cardId Card identifier to move.
 * @param {string} destinationColumnId Destination column identifier.
 * @returns {{cards: Array<object>}} Updated immutable state.
 * @throws {Error} When the card or destination does not exist.
 */
export function moveCard(state, cardId, destinationColumnId) {
  const destinationExists = COLUMNS.some(
    (column) => column.id === destinationColumnId,
  );
  const cardExists = state.cards.some((card) => card.id === cardId);

  if (!destinationExists) {
    throw new Error(`Cannot move card: unknown column "${destinationColumnId}".`);
  }

  if (!cardExists) {
    throw new Error(`Cannot move card: unknown card "${cardId}".`);
  }

  return {
    cards: state.cards.map((card) =>
      card.id === cardId ? { ...card, columnId: destinationColumnId } : { ...card },
    ),
  };
}

/**
 * Adds a validated card to the board without mutating existing state.
 * @param {{cards: Array<object>}} state Current board state.
 * @param {string} cardId Unique identifier generated by the controller.
 * @param {object} input Untrusted card form input.
 * @returns {{cards: Array<object>}} State containing the new card.
 * @throws {Error} When the identifier or input is invalid.
 */
export function addCard(state, cardId, input) {
  if (typeof cardId !== "string" || cardId.length === 0) {
    throw new Error("Cannot add card: a valid identifier is required.");
  }

  if (state.cards.some((card) => card.id === cardId)) {
    throw new Error(`Cannot add card: identifier "${cardId}" already exists.`);
  }

  return {
    cards: [...state.cards.map((card) => ({ ...card })), normalizeCard(cardId, input)],
  };
}

/**
 * Replaces editable fields on one card without mutating existing state.
 * @param {{cards: Array<object>}} state Current board state.
 * @param {string} cardId Existing card identifier.
 * @param {object} input Untrusted card form input.
 * @returns {{cards: Array<object>}} State containing the updated card.
 * @throws {Error} When the card or input is invalid.
 */
export function updateCard(state, cardId, input) {
  if (!state.cards.some((card) => card.id === cardId)) {
    throw new Error(`Cannot update card: unknown card "${cardId}".`);
  }

  const updatedCard = normalizeCard(cardId, input);
  return {
    cards: state.cards.map((card) =>
      card.id === cardId ? updatedCard : { ...card },
    ),
  };
}

/**
 * Removes one card without mutating existing state.
 * @param {{cards: Array<object>}} state Current board state.
 * @param {string} cardId Existing card identifier.
 * @returns {{cards: Array<object>}} State without the removed card.
 * @throws {Error} When the card does not exist.
 */
export function deleteCard(state, cardId) {
  if (!state.cards.some((card) => card.id === cardId)) {
    throw new Error(`Cannot delete card: unknown card "${cardId}".`);
  }

  return {
    cards: state.cards
      .filter((card) => card.id !== cardId)
      .map((card) => ({ ...card })),
  };
}

/**
 * Validates and normalizes card input into a safe serializable record.
 * @param {string} cardId Card identifier to preserve.
 * @param {object} input Untrusted card form input.
 * @returns {object} Normalized card record.
 * @throws {Error} When any field violates board constraints.
 */
function normalizeCard(cardId, input) {
  const title = typeof input?.title === "string" ? input.title.trim() : "";
  const description =
    typeof input?.description === "string" ? input.description.trim() : "";
  const columnId = input?.columnId;

  if (title.length === 0 || title.length > CARD_TITLE_MAX_LENGTH) {
    throw new Error(
      `Card title must be between 1 and ${CARD_TITLE_MAX_LENGTH} characters.`,
    );
  }

  if (description.length > CARD_DESCRIPTION_MAX_LENGTH) {
    throw new Error(
      `Card description must be ${CARD_DESCRIPTION_MAX_LENGTH} characters or fewer.`,
    );
  }

  if (!COLUMNS.some((column) => column.id === columnId)) {
    throw new Error(`Cannot save card: unknown column "${columnId}".`);
  }

  return { id: cardId, title, description, columnId };
}
